### ISSUE TITLE
[Meta] Add a web renderer

### ISSUE THREAD

**Issue by twidi** [twidi/streamdeckfs#54]
Will be done in 3 steps:

- [x] Handle fake decks #55  
- [x] handle configured but not plugged-in decks #56 
- [x] handle fake decks #57
